config/routes.rb
Rails.application.routes.draw do
  root 'home#homepage'
  get 'homepage', to: 'home#homepage'
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:show] do
    resources :gardens, only: [:show, :index, :new, :create]
  end

  resources :garden_plants, only: [:new, :create, :update, :destroy]

  resources :plants, only: [:show, :index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/garden.rb
class Garden < ApplicationRecord
  belongs_to :user
  has_many :garden_plants
  has_many :plants, through: :garden_plants

  validates :name, presence: true
  validates :location, presence: true
end

app/models/garden_plant.rb
class GardenPlant < ApplicationRecord
  belongs_to :garden
  belongs_to :plant

  validates :quantity, numericality: { only_integer: true, greater_than: 0 }

  # def formatted_plant_date
  #   created_at.strftime("%B %d, %Y")
  # end
end

app/models/plant.rb
class Plant < ApplicationRecord
  has_many :garden_plants
  has_many :gardens, through: :garden_plants

  validates :name, presence: true, uniqueness: true
  validates :scientific_name, presence: true, uniqueness: true
  validates :plant_type, presence: true

  scope :edible_plants, -> { where(edible: true) }
  scope :safe_for_pets, -> { where(pet_safe: true) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :gardens
  has_many :plants, through: :gardens
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/garden_plants_controller.rb
class GardenPlantsController < ApplicationController
  def new
    @garden_plant = GardenPlant.new
    @gardens = current_user.gardens
    @plants = Plant.all
  end

  def update
    @garden_plant = GardenPlant.find(params[:id])
    if @garden_plant.update(last_watered: Date.current)
      redirect_to user_garden_path(@garden_plant.garden), notice: "Plant watered successfully!"
    else
      redirect_to user_garden_path(@garden_plant.garden), alert: "Failed to water the plant."
    end
  end

  def destroy
    garden_plant = GardenPlant.find(params[:id])

    if garden_plant
      garden = garden_plant.garden
      garden_plant.destroy!
      redirect_to user_gardens_path(garden)
    else
      redirect_to user_gardens_path(current_user)
    end
  end

  def create
    @garden_plant = GardenPlant.new(garden_plant_params)
    @gardens = Garden.all
    @plants = Plant.all

    if @garden_plant.save
      redirect_to user_gardens_path(current_user), notice: "Successfully planted."
    else
      render :new, status: :unprocessable_entity
    end
  end

private

  def garden_plant_params
    params.require(:garden_plant).permit(:last_watered, :quantity, :plant_id, :garden_id)
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def index
    @gardens = current_user.gardens
  end

  def show
    @garden = current_user.gardens.find(params[:id])
  end

  def new
    @garden = Garden.new
  end

  def create
    @garden = Garden.new(garden_params)

    if @garden.save
      redirect_to user_gardens_path, notice: "garden was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

private

  def garden_params
    params.require(:garden).permit(:name, :location, :notes, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[homepage]
  def homepage; end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def index
    @plants = Plant.all
    if params[:sort] == "edible"
      @plants = @plants.edible_plants
    elsif params[:sort] == "pet_safe"
      @plants = @plants.safe_for_pets
    end
  end

  def show
    @plant = Plant.find(params[:id])
  end

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)

    if @plant.save
      redirect_to plants_path, notice: "Plant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

private

  def plant_params
    params.require(:plant).permit(:name, :scientific_name, :edible, :pet_safe, :plant_type, :description)
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: %i[username])
      devise_parameter_sanitizer.permit(:account_update, keys: %i[username])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/garden_plants/new.html.erb
 Plant something!
<%= form_with model: @garden_plant, local: true do |f| %>

  <%= render 'devise/shared/error_messages', object: @garden_plant %>

  <label>Select Garden:</label>
  <%= f.select :garden_id, options_from_collection_for_select(@gardens, :id, :name), prompt: 'Choose a Garden' %><br />

  <label>Select Plant:</label>
  <%= f.select :plant_id, options_from_collection_for_select(@plants, :id, :name), prompt: 'Choose a Plant' %><br />

  <label>Quantity of plant: <%= f.text_field :quantity %></label><br />


  <%= f.submit "Plant Something!" %>

<% end %>

app/views/gardens/index.html.erb
<h1>All Gardens</h1>

<ul>
  <% @gardens.each do |garden| %>
    <li><%= link_to garden.name, user_garden_path(garden.user, garden) %></li>
  <% end %>
</ul>

app/views/gardens/new.html.erb
Tell us about the new garden bed!
<%= form_with model: [current_user, @garden], local: true do |f| %>

  <%= render 'devise/shared/error_messages', object: @garden %>

  <label>Garden Name: <%= f.text_field :name %></label><br />

  <label>Location: <%= f.text_field :location %></label><br />

  <label>Notes: <%= f.text_area :notes, placeholder: "Add any notes about the garden bed..." %></label><br />

  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.submit "Add Garden" %>

<% end %>

app/views/gardens/show.html.erb
<h1><%= @garden.name %></h1>
<p> Location: <i><%= @garden.location %></i></p>
<h3>Plants you'll find here:</h3>
<ul>
  <% @garden.garden_plants.each do |gardenplant| %>
    <li><%= gardenplant.quantity %> <%= link_to gardenplant.plant.name, plant_path(gardenplant.plant) %> Planted on: <i> <%= gardenplant.formatted_plant_date %>  </i>
      <p> Last watered: <%= gardenplant.last_watered %> <%= button_to 'Water plant 💦', garden_plant_path(gardenplant), method: :patch, class: 'button-8' %>
      <%= button_to 'Remove Plant 🧤', garden_plant_path(gardenplant), method: :delete, class: 'button-8' %>
      </p>
    </li>
   <% end %>
</ul>

app/views/home/homepage.html.erb
<h1>Garden Guru</h1>
<%= image_tag 'logo2.webp', alt: 'Example Image', width: '300', height: '200', class: 'image-class' %>
<h3><i>Become the sage of your own garden sanctuary</i></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPlantApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= javascript_include_tag "rails-ujs" %>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      <p>Hello, <%=  current_user.username  %>!</p>
      <br />
      <br />
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      |
      <%= link_to 'Account Settings', edit_user_registration_path %>
      |
      <%= link_to 'My Profile', user_path(current_user) %>
    <% else %>
      <%= link_to 'Login', new_user_session_path %>
      <%= link_to 'SignUp', new_user_registration_path %>
    <% end %>
    <br />
    <br />
      <div class="center-content">
        <%= yield %>
      </div>
    <%= link_to 'Go Home', homepage_path %>
  </body>
</html>

app/views/plants/index.html.erb
<h1>All Plants</h1>

<%= form_with url: plants_path, method: :get, local: true do %>
  <div>
    <label>Sort by:</label><br>
    <%= check_box_tag 'sort', 'edible', params[:sort] == 'edible' %>
    <%= label_tag 'sort', 'Edible Plants' %><br>

    <%= check_box_tag 'sort', 'pet_safe', params[:sort] == 'pet_safe' %>
    <%= label_tag 'sort', 'Safe for Pets' %><br>

    <%= submit_tag 'Sort' %>
  </div>
<% end %>

<ul>
  <% @plants.each do |plant| %>
    <li><%= link_to plant.name, plant %></li>
  <% end %>
</ul>

app/views/plants/new.html.erb
 Tell us about the plant!
<%= form_with model: @plant, local: true do |f| %>

  <%= render 'devise/shared/error_messages', object: @plant %>

  <label>Plant Name: <%= f.text_field :name %></label><br />

  <label>Scientific Name: <%= f.text_field :scientific_name %></label><br />

  <label>Plant Description: <%= f.text_area :description %></label><br />

  <label>Plant Type:</label><br />
  <%= f.select :plant_type, options_for_select(['Herb', 'Flower', 'Tree', 'Vegetable', 'House Plant']), prompt: 'Select a plant type' %>
  <br />
  <label>Edible?: <%= f.check_box :edible %></label><br />

  <label>Pet Safe?: <%= f.check_box :pet_safe %></label><br />

  <%= f.submit "Add Plant" %>

<% end %>

app/views/plants/show.html.erb
<h1><%= @plant.name %></h1>
<h2>Scientific Name: <i><%= @plant.scientific_name %></i></h2>
<p><%= @plant.description %></p>

app/views/users/show.html.erb
<h1><%= current_user.username %>'s Profile</h1>

<br />
<%= button_to '🌱View all gardens🌱', user_gardens_path(@user), method: :get, class: 'button-8' %>
<br />
<br />

<%= button_to '🍃Till new garden🍃', new_user_garden_path(@user), method: :get, class: 'button-8' %>
<br />
<br />

<%= button_to '🪴View all plants🪴', plants_path, method: :get, class: 'button-8' %>
<br />
<br />

<%= button_to '📣Tell us about a new plant📣', new_plant_path, method: :get, class: 'button-8' %>
<br />
<br />

<%= button_to '🧤Plant something in a garden🧤', new_garden_plant_path, method: :get, class: 'button-8' %>
<br />
<br />